---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# We're going to start at the corner that has the 90 degrees
gimmie_shape <- function(start_x, start_y, square_len, 
                         hyp_prop = runif(n = 1, min = 0, max = 1), 
                         prot_amt = square_len * 0.25) {
  
  # Picking a point on the hypotenuse
  mid_x <- (1-hyp_prop) * (start_x)            + hyp_prop * (start_x+square_len)
  mid_y <- (1-hyp_prop) * (start_y+square_len) + hyp_prop * (start_y)
  
  # Picking a degree to protrude out
  right_angle <- atan2(start_y - start_y+square_len, start_x+square_len - start_x)
  angle_offset <- -0.384 #runif(n = 1, min = -0.5, max = 0.5) # The offset should be set up so that
  angle <- right_angle + angle_offset*pi                      # the closer hyp_prop is to either ends,
                                                              # it should steer away the angle from
  mid_x_mod <- mid_x + cos(angle)*prot_amt                    # each direction
  mid_y_mod <- mid_y + sin(angle)*prot_amt
                                                              # In the same vein, I should make prot_amt
  tibble(                                                     # to be not so much towards each vertexes
    x = c(start_x, start_x, mid_x_mod, start_x + square_len),
    y = c(start_y, start_y + square_len, mid_y_mod, start_y),
    group = paste0("start_x->", start_x, "start_y->", start_y, "hyp_prop->", hyp_prop, "prot_amt->", prot_amt),
    clr = sample(letters[1:4], size = 1),
    hyp_prop = hyp_prop,
    angle_offset = angle_offset
  )
}

my_clrs <-c("#FFAE00", "#008E9E", "#004E9D", "#F28973")

my_df <- crossing(
  start_x = 1,
  start_y = 1,
  square_len = 0.8
) %>% 
  # mutate(hyp_prop = 0.5) %>% 
  pmap_dfr(gimmie_shape) 

my_df %>% 
  ggplot(aes(x, y, group = group, fill = clr)) +
  geom_polygon() +
  coord_equal() +
  scale_fill_manual(values = my_clrs) +
  theme(legend.position = "none")
```

```{r}
gimmie_shape(start_x = 1, start_y = 1, square_len = 0.8, hyp_prop = 0.917) %>% 
  ggplot(aes(x, y, group = group, fill = clr)) + 
  geom_polygon() +
  geom_point() +
  coord_equal() +
  theme(legend.position = "none")
```

