---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
source(here::here("week09", "my-functions.R"))
```

K, the idea is to generate two sets of squares, one inner, one outer.

We're going to gradient-fill the space between the inner and the outer square.
- Starting from a side of the outer square, draw some lines towards the same side, on the inner square.
- Now need to crowd the squares to certain direction, and randomize the lines (i can filter out when x/xend is same)


```{r}
outer_grid <- generate_initial_grid_coords(num_row = 5, square_thickness = 1, grid_thickness = 0.2)

shrunk_grid <- outer_grid %>% 
  transmute(new_x_coords = map2(x, xend, shrink_grid_coords, shrink_by = 0.5, x_or_y = "x"),
            new_y_coords = map2(y, yend, shrink_grid_coords, shrink_by = 0.5, x_or_y = "y")) %>% 
  unnest_wider(new_x_coords) %>% 
  unnest_wider(new_y_coords)

outer_grid_plot_ready <- outer_grid %>% 
  mutate(square_id = row_number()) %>% 
  pmap_dfr(make_vertices)

shrunk_grid_plot_ready <- shrunk_grid %>% 
  mutate(square_id = row_number()) %>% 
  pmap_dfr(make_vertices)

my_n_lines <- 40

outer_gradient_points <- outer_grid_plot_ready %>% 
  pmap(get_gradient_points, dat = outer_grid_plot_ready, n_lines = my_n_lines)

shrunk_gradient_points <- shrunk_grid_plot_ready %>% 
  pmap(get_gradient_points, dat = shrunk_grid_plot_ready, n_lines = my_n_lines)

gradient_lines <- connect_gradient_points(outer_gradient_points, shrunk_gradient_points, min_length = 0.4)

p <- ggplot() +
  geom_polygon(data = outer_grid_plot_ready, aes(x = x, y = y, group = square_id), fill = "#e9f7f7") +
  geom_polygon(data = shrunk_grid_plot_ready, aes(x = x, y = y, group = square_id), fill = "#e9f7f7") +
  geom_segment(data = gradient_lines, aes(x = x, xend = new_xend, y = y, yend = new_yend), color = "#072f62") +
  coord_equal() +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "#072f62", color = "#072f62")
  )

p

# ggsave(
#   here::here("week09", "progress.png"),
#   plot = p,
#   device = ragg::agg_png,
#   dpi = 300,
#   units = "px",
#   height = 3000,
#   width = 3000
# )
```

