---
title: "Week 6 #RecreationThursday"
author: "Jiwan Heo"
output: html_document
---

```{r initial_canvas}
library(tidyverse)
library(rlang)

# Criss-cross grid
make_canvas <- function(n_row) {
  grid1 <- crossing(x0 = 1:n_row, y0 = 1:n_row)
  grid2 <- crossing(x0 = 1.5:(n_row-0.5), y0 = 1.5:(n_row-0.5))
  
  bind_rows(grid1, grid2) %>% 
    arrange(x0, y0)
}

my_canvas <- make_canvas(20) %>% 
  mutate(
    a = 0.25,
    b = 0.25, 
    angle = 0
  ) 
```

```{r plot_function_to_canvas}
# Take an expression as input (drawing function)
# Going column by column, calculate the result of the expression for every x0
# Pick the closets y0 on the canvas, that's closest to the result of the expression
# For the rest of the points (vertical line), calculate the distance to the picked point. 
draw_func <- function(canvas, expr) {
  expr <- enquo(expr)
  eval_res <- eval_tidy(expr, canvas)
  canvas_nrow <- canvas %>% filter(x0 == 1) %>% nrow() # To scale the distance
  
  distance_calculated <- canvas %>% 
    mutate(answer = eval_res) %>% 
    mutate(diff = abs(answer - y0)) %>% 
    group_by(x0) %>% 
    mutate(closest = diff == min(diff)) %>% 
    mutate(dist = map_dbl(row_number(), ~ abs(.x - min(which(closest == TRUE))))) %>% 
    ungroup() 
  
  distance_scaled <- distance_calculated %>%  
    mutate(dist = dist / canvas_nrow) %>% 
    mutate(clr  = hsv(h = 0, s = 0, v = dist)) %>% 
    mutate(a = a - a*dist) %>% # Height/width scaled by dist
    select(-c(answer, diff))
}
```

```{r setup_for_ggplot}
# Couple different functions to plot
my_func <- expr(sin(x0) * 10 + 10)
my_func <- expr(x0)
my_func <- expr(sin(x0 / 20 * pi) * 20)

my_drawn_canvas <- draw_func(canvas = my_canvas, expr = !!my_func)

my_clrs <- my_drawn_canvas %>% distinct(clr) %>% as_vector()
my_clrs <- my_clrs %>% set_names(nm = my_clrs)
```

```{r lets_plot}
my_drawn_canvas %>% 
  ggplot() +
  ggforce::geom_ellipse(aes(x0 = x0, 
                            y0 = y0, 
                            a = a, 
                            b = b, 
                            angle = angle, 
                            fill = clr), 
                        color = NA) +
  coord_equal() +
  theme_void() +
  theme(
    legend.position = "none"
  ) + 
  scale_fill_manual(values = my_clrs)
```